service: import-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::uploaded-bucket-gwjf"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::uploaded-bucket-gwjf/*"

resources:
  Resources:
    AuthorizerApiGatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          "gatewayresponse.header.Access-Control-Allow-Origin": "'*'"
          "gatewayresponse.header.Access-Control-Allow-Headers": "'*'"
        ResponseType: "DEFAULT_4XX"
        RestApiId: "dbmwkl2fzl"

functions:
  importProductsFile:
    handler: src/handlers/importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: get
          request:
            parameters:
              querystrings:
                name: true
          cors:
            origin: '*'
          authorizer:
            arn: arn:aws:lambda:eu-west-1:645756223154:function:authorization-service-dev-authorizer
            name: authorization-service-dev-authorizer

  importFileParser:
    handler: src/handlers/importFileParser.importFileParser
    events:
      - s3:
          bucket: uploaded-data-bucket
          event: s3:ObjectCreated:*
          rules: 
            - prefix: uploaded/
          existing: true
