service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

functions:
  get:
    handler: src/index.mainHandler
    events:
      - http:
          path: /products
          method: get
      - http:
          path: /products/{productId}
          method: get

